apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-files
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  http.yaml: |
    use_x_forwarded_for: true
    trusted_proxies:
      - 10.0.0.0/8