name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # token: ${{ secrets.PYTHON_API_TOKEN }}
          python-version: "3.10"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1
        with:
          version: v3.5.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "$changed"
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml --debug

  # lint-test-install:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # https://kubernetes.io/releases/
  #       k8s:
  #         - v1.21.2
  #         - v1.22.15
  #         - v1.23.12
  #         - v1.24.6
  #         - v1.25.2
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - name: Set up chart-testing
  #       uses: helm/chart-testing-action@v2.3.1
  #       with:
  #         version: v3.5.1

  #     - name: Run chart-testing (list-changed)
  #       id: list-changed
  #       run: |
  #         changed=$(ct list-changed --config ct.yaml)
  #         if [[ -n "$changed" ]]; then
  #           echo "$changed"
  #           echo "::set-output name=changed::true"
  #         fi

  #     - name: Create kind cluster
  #       if: steps.list-changed.outputs.changed == 'true'
  #       uses: helm/kind-action@v1.4.0
  #       with:
  #         kubectl_version: ${{ matrix.k8s }}
  #         verbosity: 10

  #     - name: Run chart-testing (install)
  #       run: ct install --config ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run helm-docs
        env:
          HELM_DOCS_VERSION: "1.11.0"
        run: |
          curl --silent --show-error --fail --location --output /tmp/helm-docs.tar.gz https://github.com/norwoodj/helm-docs/releases/download/v"${HELM_DOCS_VERSION}"/helm-docs_"${HELM_DOCS_VERSION}"_Linux_x86_64.tar.gz
          tar -xf /tmp/helm-docs.tar.gz helm-docs
          ./helm-docs
          git diff --exit-code
